# Generated by Django 5.2.1 on 2025-11-17 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mythpedia', '0007_alter_favoritemythology_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MythStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'histoire")),
                ('slug', models.SlugField(blank=True, help_text='Identifiant URL (auto-généré à partir du titre si laissé vide)', max_length=210, unique=True)),
                ('summary', models.TextField(blank=True, help_text="Court résumé de l'histoire", verbose_name="Résumé de l'histoire")),
                ('full_text', models.TextField(blank=True, help_text="Texte complet de l'histoire", verbose_name="Texte complet de l'histoire")),
                ('themes', models.CharField(blank=True, help_text="Thèmes de l'histoire (séparés par des virgules)", max_length=300, null=True)),
                ('image_url', models.URLField(blank=True, help_text="URL de l'image illustrative (ex: Imgur)", max_length=300, null=True)),
                ('characters', models.ManyToManyField(blank=True, help_text='Personnages apparaissant dans cette histoire', related_name='featured_in_stories', to='mythpedia.character')),
                ('mythology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='mythpedia.mythology')),
            ],
            options={
                'verbose_name': 'Histoire/Mythe',
                'verbose_name_plural': 'Histoires/Mythes',
                'ordering': ['mythology', 'title'],
            },
        ),
    ]
