# Generated by Django 5.2.1 on 2025-11-17 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mythpedia', '0008_mythstory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('MYTHOLOGY', 'Mythologie'), ('CHARACTER', 'Personnage'), ('STORY', 'Histoire/Mythe')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('text', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Approuvé')),
                ('content_type_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_object', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mythpedia_c_content_170ed6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('MYTHOLOGY', 'Mythologie'), ('CHARACTER', 'Personnage'), ('STORY', 'Histoire/Mythe')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('score', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_for_object', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='mythpedia_r_content_813b26_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
